### ISSUE TITLE
Dialog does not work in <React.StrictMode>

### ISSUE THREAD

**Issue by MetteSejrThomsen** [rmwc/rmwc#1068] opened 2023-09-29 10:44 UTC
- What RMWC Version are you using [major.minor.patch]: "@rmwc/dialog": "^8.0.8",

- Name your build system [Webpack, Rollup...]: create-react-app

- Describe the bug with as much detail as possible:
- Dialog is not rendered in strictmode when setting open to true via a butten. Used the Standard Usage example from https://rmwc.io/dialogs.

- What happened, and what was supposed to happen:
- Dialog was shown in the DOM when inspecting the page, but was not rendered visually. Removing strictmode made it appear.

**Comment by b-d-m-p** [comment] 2023-10-26 08:24
@MetteSejrThomsen Thanks for the issue! We are working on the v14 release, but we will take a deep look at this right after!

**Comment by jensborch** [comment] 2024-01-04 09:33
This is a duplicate of https://github.com/rmwc/rmwc/issues/815

**Closed by jensborch** 2024-01-04 09:33 UTC
Labels: duplicate
